using CommunityToolkit.Maui.Animations;
using ConcertJournal.Models;            // for Concert
using ConcertJournal.Views;             // for navigation pages
using Microsoft.Maui.Controls;
using System;
using System.Collections.ObjectModel;
using System.Linq;                      // <= needed for LINQ
using System.Threading;
using System.Threading.Tasks;

namespace ConcertJournal;

public partial class MainPage : ContentPage
{
    // ----- UI bindings -----

    // Show/hide stats frame
    bool _hasConcerts;
    public bool HasConcerts
    {
        get => _hasConcerts;
        set
        {
            _hasConcerts = value;
            OnPropertyChanged();
            OnPropertyChanged(nameof(ShowEmptyHints));   // already there
            OnPropertyChanged(nameof(ShowWelcomeHero));  // NEW
        }
    }

    public bool ShowWelcomeHero => !IsAddingConcert;

    // Indicate that the AddConcert flow is active
    bool _isAddingConcert;
    public bool IsAddingConcert
    {
        get => _isAddingConcert;
        set
        {
            _isAddingConcert = value;
            OnPropertyChanged();
            OnPropertyChanged(nameof(ShowEmptyHints));   // already there
            OnPropertyChanged(nameof(ShowWelcomeHero));  // NEW
        }
    }

    // Combined flag used by XAML to show the two text boxes + arrow
    public bool ShowEmptyHints => !HasConcerts && !IsAddingConcert;

    // Status counts
    int _happenedCount, _scheduledCount, _totalCount;
    public int HappenedCount
    {
        get => _happenedCount;
        set { _happenedCount = value; OnPropertyChanged(); }
    }
    public int ScheduledCount
    {
        get => _scheduledCount;
        set { _scheduledCount = value; OnPropertyChanged(); }
    }
    public int TotalCount
    {
        get => _totalCount;
        set { _totalCount = value; OnPropertyChanged(); }
    }

    // Top lists for stats panel (your XAML binds to these)
    public ObservableCollection<StatRow> PerformerStats { get; } = new();
    public ObservableCollection<StatRow> LocationStats { get; } = new();
    public ObservableCollection<StatRow> DateStats { get; } = new();   // <= FIXED
    public ObservableCollection<Concert> Concerts { get; } = new();

    public MainPage()
    {
        // Fix for CS0103: Ensure InitializeComponent is available
        // This method is generated by the XAML compiler and requires the partial class and correct inheritance.
        InitializeComponent();
        BindingContext = this;
    }

    // Load data each time the page appears
    protected override async void OnAppearing()
    {
        base.OnAppearing();

        var concerts = await App.Database.GetConcertsAsync();

        Concerts.Clear();
        if (concerts != null)
            foreach (var c in concerts)
                Concerts.Add(c);

        HasConcerts = Concerts.Count > 0;

        BuildStatusCounts(concerts ?? new List<Concert>());
    }

    // ---- Bottom bar navigation ----
    private async void OnStartPageClicked(object sender, EventArgs e)
        => await Navigation.PopToRootAsync();

    private async void OnAddConcertClicked(object sender, EventArgs e)
        => await Navigation.PushAsync(new AddConcertPage(), false);

    private async void OnConcertListClicked(object sender, EventArgs e)
        => await Navigation.PushAsync(new ConcertListPage(), false);

    // ===== Stats helpers =====
    private void BuildStatusCounts(IList<Concert> concerts)
    {
        HappenedCount = ScheduledCount = 0;
        TotalCount = concerts?.Count ?? 0;
        if (concerts == null || concerts.Count == 0) return;

        foreach (var c in concerts)
        {
            var status = GetStatus(c); // "happened" | "scheduled" | ""
            switch (status)
            {
                case "scheduled": ScheduledCount++; break;
                case "happened": HappenedCount++; break;
            }
        }
    }
    private async void OnSettingsPageClicked(object sender, EventArgs e)
    {
        await Navigation.PushAsync(new SettingsPage(), false);
    }


    private static string GetStatus(Concert c)
    {
        if (c == null || !c.Date.HasValue)
            return "";

        var d = c.Date.Value.Date;

        if (d <= DateTime.Today)
            return "happened";   // past or today
        else
            return "scheduled";  // future
    }



    // Row model for the small stat lists
    public record StatRow(string Name, int Count)
    {
    };

    private async void OnCardTapped(object sender, TappedEventArgs e)
    {
        if (e.Parameter is Concert c)
        {
            await Navigation.PushAsync(new ConcertDetailsPage(c));
        }
    }
    public async void Animate()
    {
        var label = new Label();

        var fadeAnimation = new FadeAnimation();

        await fadeAnimation.Animate(label);
    }

}

